iffltool.c added and changes to Makefile
luigidifraia/iffl-system pull request #2
Opened 2022-01-07 07:08 UTC by vschwaberow

2022-05-13 06:42 UTC, vschwaberow commented
No interest in this pull?

2022-05-13 20:12 UTC, luigidifraia commented
> No interest in this pull?

I had left a few comments, requesting changes. Have you had a chance to think about them?

2022-05-15 08:42 UTC, vschwaberow commented
No, because I haven't seen them, Luigi. Where did you commit them / issue them? Any link?

2022-05-15 11:37 UTC, luigidifraia commented
> No, because I haven't seen them, Luigi. Where did you commit them / issue them? Any link?

I didn't make any changes myself. If you look at the review above, you can:
1. reply to my comments, and then either:
a. make changes, in line with those comments of mine that you deem useful, or 
b. not make any change but provide insights on why no change is required.

2022-05-15 13:29 UTC, vschwaberow commented
Did you submitted your review because I really can't see it. Could you check this? Thanks. The review tab tells me : No review.

2022-05-15 19:20 UTC, luigidifraia requested changes

2022-05-15 19:20 UTC, luigidifraia commented on iffl-tools/iffltool.c
> +    printf("  help\t\t\t\tPrint this help\n");
It doesn't appear the code below handles the "help" command. It seems to handle the "-h" switch.

2022-05-15 19:20 UTC, luigidifraia commented on iffl-tools/iffltool.c
> +    else if (argc > 2 && strncmp(argv[1], "create", 2) == 0)
You've consistently used 2 as the third argument in `strncmp()`. Is it a partial match by design you are requesting?

2022-05-15 19:20 UTC, luigidifraia commented on iffl-tools/iffltool.c
> +    printf("Usage: iffltool [options]\n");
Rather than `[options]` I guess this might read `<command> [filename(s)]` (i.e. only one command per run and an optional variable number of filenames)?

2022-05-15 19:22 UTC, luigidifraia commented
> Did you submitted your review because I really can't see it. Could you check this? Thanks. The review tab tells me : No review.

My comments should now be visible under the "Conversation" tab.

2022-05-28 08:36 UTC, vschwaberow commented on iffl-tools/iffltool.c
> +    printf("  help\t\t\t\tPrint this help\n");
Yups. Mistake. Fixed it in 5b2b2d124ef8d0ff6544ad3c601de16122ac7521

2022-05-28 08:36 UTC, vschwaberow commented on iffl-tools/iffltool.c
> +    else if (argc > 2 && strncmp(argv[1], "create", 2) == 0)
Of cause nonsense checking. I addressed this in 20a2b1727a79f7776b0e729c2d80efd7de51e4fd

2022-05-28 08:37 UTC, vschwaberow commented on iffl-tools/iffltool.c
> +    printf("Usage: iffltool [options]\n");
Adressed in 5b2b2d124ef8d0ff6544ad3c601de16122ac7521

2022-06-20 09:38 UTC, closed without merging